name: .NET Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest' # Use latest or specify a version like '16.9'

    - name: Restore dependencies
      run: msbuild /t:restore

    - name: Build with MSBuild
      run: msbuild /t:build

    - name: Run tests
      run: msbuild /t:test
